name: fruitbox
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.6
  modal_progress_hud_nsn: ^0.5.1
  animated_text_kit: ^4.2.2
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  provider: ^6.1.2
  rflutter_alert: ^2.0.7
  badges: ^3.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.1
  sqflite: ^2.3.3+1
  email_validator: ^3.0.0
  cloud_firestore: ^5.2.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  firebase_database: ^11.0.4
  google_sign_in: ^6.2.1
  flutter_animate: ^4.5.0
  firebase_app_check: ^0.3.0+4
  flutter_svg: ^2.0.10+1
  persistent_shopping_cart: ^0.0.7
  cached_network_image: ^3.4.0
  iconsax: ^0.0.8
  hive: ^2.2.3
  geocoding: ^2.0.5
  pay: ^2.0.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
