// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThEHmGLr6IgMX8a07u-07Zuwwt0OMTko',
    appId: '1:505474410616:web:c8c036e9722913b139a58d',
    messagingSenderId: '505474410616',
    projectId: 'fruitbox-1',
    authDomain: 'fruitbox-1.firebaseapp.com',
    storageBucket: 'fruitbox-1.appspot.com',
    measurementId: 'G-QB1KTHKP8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVjhVt7JRC6QXU5Xrys-ZNCin5m74VYCI',
    appId: '1:505474410616:android:c1b95ddfa389d12639a58d',
    messagingSenderId: '505474410616',
    projectId: 'fruitbox-1',
    storageBucket: 'fruitbox-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhpaEXmS8uV2GqtU6Qdbo1LkJEKzktVE',
    appId: '1:505474410616:ios:28099309d05a3fda39a58d',
    messagingSenderId: '505474410616',
    projectId: 'fruitbox-1',
    storageBucket: 'fruitbox-1.appspot.com',
    iosBundleId: 'com.uzeetech.fruitbox',
  );
}
